-- =====================================================
-- BrainCoin Seed Data: Subjects only
-- Questions are generated by Claude AI on demand and
-- cached in the DB -- no static question data here.
-- =====================================================

INSERT INTO subjects (name, name_en, name_de, slug, emoji, grades) VALUES
  ('Mathematik',         'Mathematics',        'Mathematik',          'math',        E'\U0001F532', ARRAY['4','5','6','7','8','9']),
  ('Englisch',           'English',            'Englisch',            'english',     E'\U0001F1EC\U0001F1E7', ARRAY['4','5','6','7','8','9']),
  ('Ukrainische Sprache','Ukrainian language', 'Ukrainische Sprache', 'ukrainian',   E'\U0001F1FA\U0001F1E6', ARRAY['4','5','6','7','8','9']),
  ('Geschichte',         'History',            'Geschichte',          'history',     E'\U0001F4DC', ARRAY['5','6','7','8','9']),
  ('Naturkunde',         'Natural science',    'Naturkunde',          'science',     E'\U0001F331', ARRAY['4','5','6']),
  ('Chemie',             'Chemistry',          'Chemie',              'chemistry',   E'\U0001F9EA', ARRAY['7','8','9']),
  ('Physik',             'Physics',            'Physik',              'physics',     E'\u269B\uFE0F', ARRAY['7','8','9']),
  ('Biologie',           'Biology',            'Biologie',            'biology',     E'\U0001F9EC', ARRAY['4','5','6','7','8','9']),
  ('Geographie',         'Geography',          'Geographie',          'geography',   E'\U0001F30D', ARRAY['4','5','6','7','8','9']),
  ('Programmierung',     'Programming',        'Programmierung',      'programming', E'\U0001F4BB', ARRAY['4','5','6','7','8','9']),
  ('Deutsch',            'German language',    'Deutsch',             'german',      E'\U0001F1E9\U0001F1EA', ARRAY['4','5','6','7','8','9'])
ON CONFLICT (slug) DO UPDATE SET
  name   = EXCLUDED.name,
  grades = EXCLUDED.grades;
